/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

interface P {
  isMobile?: boolean;
}

export function Kalygo3dModel(props: P) {
  //   @ts-ignore
  const { nodes, materials } = useGLTF("/3d_kalygo.glb");
  const ref = useRef();
  //   @ts-ignore
  useFrame((state, delta) => (ref.current.rotation.z += delta));

  console.log("materials", materials);

  return (
    <group {...props} dispose={null}>
      <mesh
        // @ts-ignore
        ref={ref}
        castShadow
        receiveShadow
        geometry={nodes.Curve.geometry}
        material={materials["SVGMat.001"]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={32}
      />
    </group>
  );
}

useGLTF.preload("/3d_kalygo.glb");
