export enum SummaryMode {
  PRIOR_TO_TRACKING_MODE = "PRIOR_TO_TRACKING_MODE",
  OVERALL = "OVERALL",
  FILE_OVERALL = "FILE_OVERALL",
  FILE_IN_CHUNKS = "FILE_IN_CHUNKS",
  EACH_FILE_OVERALL = "EACH_FILE_OVERALL",
  EACH_FILE_IN_CHUNKS = "EACH_FILE_IN_CHUNKS",
  EACH_FILE_PER_PAGE = "EACH_FILE_PER_PAGE",
  EACH_FILE_PER_PAGE_THEN_OVERALL = "EACH_FILE_PER_PAGE_THEN_OVERALL",
  EACH_FILE_OVERLAPPING_CHUNKS = "EACH_FILE_OVERLAPPING_CHUNKS",
}
